# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [55]:
import numpy as np

#### 2. Print your NumPy version.

In [56]:
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [57]:
# Method 1
a=np.random.random((2,3,5))
print(a)

[[[0.71989595 0.73803405 0.90993227 0.10592884 0.46857519]
  [0.27757189 0.20076459 0.25995467 0.56430451 0.92100504]
  [0.91418395 0.61447732 0.82257942 0.35622363 0.17242895]]

 [[0.02405377 0.48309757 0.67418038 0.57787161 0.53184059]
  [0.52447741 0.69995403 0.56697107 0.61836365 0.52547563]
  [0.67672291 0.75377983 0.27761564 0.5883783  0.24825557]]]


In [58]:
# Method 2

a=np.random.rand(2,3,5)
print(a)



[[[0.59819529 0.76148441 0.42722831 0.40834002 0.88045934]
  [0.10309774 0.32962232 0.95818893 0.2688292  0.04226258]
  [0.04561535 0.04974134 0.08696339 0.11966654 0.11459325]]

 [[0.77586574 0.9730865  0.99318257 0.19301275 0.28229872]
  [0.00920006 0.35753983 0.79842618 0.37467182 0.36246624]
  [0.8098754  0.19861949 0.79205346 0.250563   0.42077379]]]


In [59]:
# Method 3

a=np.empty((2,3,5))
print(a)

[[[0.59819529 0.76148441 0.42722831 0.40834002 0.88045934]
  [0.10309774 0.32962232 0.95818893 0.2688292  0.04226258]
  [0.04561535 0.04974134 0.08696339 0.11966654 0.11459325]]

 [[0.77586574 0.9730865  0.99318257 0.19301275 0.28229872]
  [0.00920006 0.35753983 0.79842618 0.37467182 0.36246624]
  [0.8098754  0.19861949 0.79205346 0.250563   0.42077379]]]


#### 4. Print *a*.


In [60]:
print(a)

[[[0.59819529 0.76148441 0.42722831 0.40834002 0.88045934]
  [0.10309774 0.32962232 0.95818893 0.2688292  0.04226258]
  [0.04561535 0.04974134 0.08696339 0.11966654 0.11459325]]

 [[0.77586574 0.9730865  0.99318257 0.19301275 0.28229872]
  [0.00920006 0.35753983 0.79842618 0.37467182 0.36246624]
  [0.8098754  0.19861949 0.79205346 0.250563   0.42077379]]]


In [61]:
# 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [62]:
b=np.ones((5,2,3),dtype = float)

#### 6. Print *b*.


In [63]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [64]:
print(a.size==b.size)


True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [65]:
# print(np.add(a,b))

# Can't add up a and b, because these 2 arrays have different shapes


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [66]:
# your code here

c=np.reshape(b,((2,3,5)))
print(c)




[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [67]:
# a's shape=(2,3,5)
# b's shape=(5,2,3) --> reshape (2,3,5)=c
# a and c have the same shape, thus they can add up to d


d=np.add(a,c)
print(d)


[[[1.59819529 1.76148441 1.42722831 1.40834002 1.88045934]
  [1.10309774 1.32962232 1.95818893 1.2688292  1.04226258]
  [1.04561535 1.04974134 1.08696339 1.11966654 1.11459325]]

 [[1.77586574 1.9730865  1.99318257 1.19301275 1.28229872]
  [1.00920006 1.35753983 1.79842618 1.37467182 1.36246624]
  [1.8098754  1.19861949 1.79205346 1.250563   1.42077379]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [68]:
print(a)
print('--'*40)
print(d)

[[[0.59819529 0.76148441 0.42722831 0.40834002 0.88045934]
  [0.10309774 0.32962232 0.95818893 0.2688292  0.04226258]
  [0.04561535 0.04974134 0.08696339 0.11966654 0.11459325]]

 [[0.77586574 0.9730865  0.99318257 0.19301275 0.28229872]
  [0.00920006 0.35753983 0.79842618 0.37467182 0.36246624]
  [0.8098754  0.19861949 0.79205346 0.250563   0.42077379]]]
--------------------------------------------------------------------------------
[[[1.59819529 1.76148441 1.42722831 1.40834002 1.88045934]
  [1.10309774 1.32962232 1.95818893 1.2688292  1.04226258]
  [1.04561535 1.04974134 1.08696339 1.11966654 1.11459325]]

 [[1.77586574 1.9730865  1.99318257 1.19301275 1.28229872]
  [1.00920006 1.35753983 1.79842618 1.37467182 1.36246624]
  [1.8098754  1.19861949 1.79205346 1.250563   1.42077379]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [69]:
e=np.multiply(a,c)

print(e)

[[[0.59819529 0.76148441 0.42722831 0.40834002 0.88045934]
  [0.10309774 0.32962232 0.95818893 0.2688292  0.04226258]
  [0.04561535 0.04974134 0.08696339 0.11966654 0.11459325]]

 [[0.77586574 0.9730865  0.99318257 0.19301275 0.28229872]
  [0.00920006 0.35753983 0.79842618 0.37467182 0.36246624]
  [0.8098754  0.19861949 0.79205346 0.250563   0.42077379]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [70]:
print(e==a)
#print(np.sum(e)==np.sum(a))

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [71]:
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.993182572084803
1.0092000597489976
1.4261974524914283


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [72]:

f=np.empty((2,3,5),dtype=float,order='C')

print(f)

[[[0.59819529 0.76148441 0.42722831 0.40834002 0.88045934]
  [0.10309774 0.32962232 0.95818893 0.2688292  0.04226258]
  [0.04561535 0.04974134 0.08696339 0.11966654 0.11459325]]

 [[0.77586574 0.9730865  0.99318257 0.19301275 0.28229872]
  [0.00920006 0.35753983 0.79842618 0.37467182 0.36246624]
  [0.8098754  0.19861949 0.79205346 0.250563   0.42077379]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [79]:
# For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f. 

f[(d > d_min)&(d< d_mean)]=25






# If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

f[(d < d_max)&(d> d_mean)]=75




# If a value equals to d_mean, assign 50 to the corresponding value in f. 

f[d==d_mean]=50



 
# Assign 0 to the corresponding value(s) in f for d_min in d. 
    
f[d==d_min]=0




# Assign 100 to the corresponding value(s) in f for d_max in d
f[d==d_max]=100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [80]:
print(d)

print('\n')

print(f)

[[[1.59819529 1.76148441 1.42722831 1.40834002 1.88045934]
  [1.10309774 1.32962232 1.95818893 1.2688292  1.04226258]
  [1.04561535 1.04974134 1.08696339 1.11966654 1.11459325]]

 [[1.77586574 1.9730865  1.99318257 1.19301275 1.28229872]
  [1.00920006 1.35753983 1.79842618 1.37467182 1.36246624]
  [1.8098754  1.19861949 1.79205346 1.250563   1.42077379]]]


[[['75' '75' '75' '25' '75']
  ['25' '25' '75' '25' '25']
  ['25' '25' '25' '25' '25']]

 [['75' '75' '100' '25' '25']
  ['0' '25' '75' '25' '25']
  ['75' '25' '75' '25' '25']]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [83]:
f=d.astype(np.str)
